#!/bin/bash

#- dvojdielny román, pôvodne písaný ako paródia na rytierske romány. Podáva obraz človeka a jeho večnej túžby po ideály pravdy, slobody a spravodlivosti; dvojica hlavných hrdinov Don Quijote a jeho sluha Sancho Panza predstavuje dvojaký pohľad na svet - rytierstvo čistého srdca a zdravý sedliacky rozum.
#Don Quijote číta rytierske romány, až sa z toho zblázni a chce obnoviť zašlú slávu potulného rytierstva.

Quijote sa na koňovi Rocinantovi vypraví so svojím poživačným sluhom Sanchom do sveta, aby vykonal hrdinské činy na oslavu svojej vyvolenej dámy Dulcinei z Tobosa, ktorá nieje nič viac než obyčajná žena ktorá dojí kravy. Quijote chce pomáhať chudobným a slabím, chrániť siroty a vdovy a  samozrejme konať dobro. Zažíva množstvo dobrodružstiev - dáva sa pasovať krčmárom za rytiera, o ktorom si myslí, že je hradný kastelán.

Príhody:

Quijote zaútočíl na stádo oviec, ktoré považuje za nepriateľa. 
Najznámejším jeho dobrodružstvom je boj s veternými mlynmi, ktoré považuje za obrov. 
Ale ani tieto neúspechy ho neodradily od "atustických predstav".

Nakoniec ho zválcovalo stádo svíň. Don Quijote zomrel, ale jeho ideály a čudné predstavy pretrvávajú, pretože Sancho mu sľúbi, že v jeho činoch bude pokračovať.
